### ISSUE TITLE
Eigen / Core

### ISSUE THREAD

**Issue by GusakIurii** [bolderflight/mpu9250#2]
I don’t understand where they come from:
#include "Eigen / Core"
#include "Eigen / Dense"
#include "core / core.h"

In the Compiler, the error is: fatal error: Eigen / Core: No such file or directory

**Comment by GusakIurii** [comment]
I want to try a function:
Eigen :: Vector3f gyro_radps () Returns the gyro data from the Mpu9250 objects as a 3-dimensional vector in units of rad / s.

But I don't have Eigen files, can you share this?

**Comment by flybrianfly** [comment]
How are you compiling this library? If you're using our [build tools](https://github.com/bolderflight/build-tools) or [CMake](https://github.com/bolderflight/mpu9250/blob/main/CMakeLists.txt#L24), it will pull the dependencies automatically. We maintain a [mirror of the Eigen library](https://github.com/bolderflight/eigen)

**Comment by GusakIurii** [comment]
I understood. Thank.
I wanted to screw it to Arduino.
But this library is not for him)

**Comment by flybrianfly** [comment]
The Arduino version is here:
https://github.com/bolderflight/mpu9250-arduino

**Comment by GusakIurii** [comment]
Yes, I've seen this library! Thank you for such work!)
This library is the only one that works with my hardware! But I would also like to get the coordinates of the direction of the sensor not in the axes, but in the tilt angle, and the second from the Magnetometer as the direction where it is looking.
I thought it was implemented in this library, but alas ..
